/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint handler.
         * @description Returns 200 if all checks pass, 503 if any check fails.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe handler.
         * @description Always returns 200 if the process is running.
         *     Does not check dependencies - use readiness for that.
         */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe handler.
         * @description Returns 200 only if all dependencies are available.
         *     Use for Kubernetes readiness probes.
         */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query audit logs.
         * @description Search and filter audit log entries. Supports date range, user ID,
         *     event type, and resource filtering. Admin only.
         */
        get: operations["query_audit_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed health information.
         * @description Returns comprehensive health status including storage metrics.
         *     More detailed than the public health endpoint. Admin only.
         */
        get: operations["get_detailed_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system statistics.
         * @description Returns aggregate statistics about the system including wallet counts,
         *     invite usage, and storage metrics. Admin only.
         */
        get: operations["get_system_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all unique users with their resource counts.
         * @description Returns a summary of all users who have wallets, bookmarks, or recurring payments.
         */
        get: operations["list_all_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all wallets (admin view).
         * @description Returns all wallets across all users. Admin only.
         */
        get: operations["list_all_wallets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/wallets/{wallet_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reactivate a suspended wallet (admin action).
         * @description Reactivates a previously suspended wallet.
         */
        post: operations["activate_wallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/wallets/{wallet_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend a wallet (admin action).
         * @description Suspends a wallet by ID. The wallet owner cannot perform operations
         *     on suspended wallets until reactivated.
         */
        post: operations["suspend_wallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bookmarks for a wallet.
         * @description Returns all bookmarks for a wallet owned by the authenticated user.
         */
        get: operations["list_bookmarks"];
        put?: never;
        /**
         * Create a new bookmark.
         * @description Creates a bookmark in a wallet owned by the authenticated user.
         */
        post: operations["create_bookmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookmarks/{bookmark_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a bookmark.
         * @description Deletes a bookmark owned by the authenticated user.
         */
        delete: operations["delete_bookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_invite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invite/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["redeem_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_recurring_payment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payment/{recurring_payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_recurring_payment"];
        post?: never;
        delete: operations["delete_recurring_payment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payment/{recurring_payment_id}/last-paid-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_last_paid_date"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_recurring_payments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payments/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recurring_payments_today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current authenticated user's information.
         * @description This endpoint returns the identity and roles of the currently authenticated user.
         */
        get: operations["get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all wallets owned by the authenticated user. */
        get: operations["list_wallets"];
        put?: never;
        /**
         * Create a new wallet for the authenticated user.
         * @description Generates a new p256 keypair inside the SGX enclave and stores it
         *     encrypted on disk. Returns the wallet metadata (never the private key).
         */
        post: operations["create_wallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific wallet by ID.
         * @description Only returns wallets owned by the authenticated user.
         */
        get: operations["get_wallet"];
        put?: never;
        post?: never;
        /**
         * Delete (soft-delete) a wallet.
         * @description Marks the wallet as deleted. The private key is retained for potential
         *     recovery but the wallet cannot be used for new transactions.
         */
        delete: operations["delete_wallet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the balance of a wallet on the Avalanche C-Chain.
         * @description Returns native AVAX balance and any configured ERC-20 token balances.
         */
        get: operations["get_wallet_balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}/balance/native": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get only the native AVAX balance of a wallet (faster). */
        get: operations["get_native_balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response for admin user list. */
        AdminUserListResponse: {
            /** @description Total unique users. */
            total: number;
            /** @description User summaries. */
            users: components["schemas"]["AdminUserSummary"][];
        };
        /** @description Admin user summary. */
        AdminUserSummary: {
            /** @description Number of bookmarks. */
            bookmark_count: number;
            /** @description Number of recurring payments. */
            recurring_payment_count: number;
            /** @description User ID from Clerk. */
            user_id: string;
            /** @description Number of wallets owned. */
            wallet_count: number;
        };
        /** @description Admin wallet list item (shows all wallets regardless of owner). */
        AdminWalletItem: {
            /** @description When the wallet was created. */
            created_at: string;
            /** @description Owner's user ID. */
            owner_user_id: string;
            /** @description Public address. */
            public_address: string;
            /** @description Wallet status. */
            status: components["schemas"]["WalletStatus"];
            /** @description Wallet unique identifier. */
            wallet_id: string;
        };
        /** @description Response for admin wallet list. */
        AdminWalletListResponse: {
            /** @description Total count. */
            total: number;
            /** @description List of all wallets. */
            wallets: components["schemas"]["AdminWalletItem"][];
        };
        /** @description An audit log entry. */
        AuditEvent: {
            /** @description Additional details as JSON. */
            details?: Record<string, never> | null;
            /** @description Error message if operation failed. */
            error?: string | null;
            /** @description Unique event ID. */
            event_id: string;
            /** @description Type of event. */
            event_type: components["schemas"]["AuditEventType"];
            /** @description IP address of the request (if available). */
            ip_address?: string | null;
            /** @description Resource affected (wallet_id, bookmark_id, etc.). */
            resource_id?: string | null;
            /** @description Resource type (wallet, bookmark, etc.). */
            resource_type?: string | null;
            /** @description Whether the operation succeeded. */
            success: boolean;
            /**
             * Format: date-time
             * @description When the event occurred.
             */
            timestamp: string;
            /** @description User who triggered the event (if known). */
            user_id?: string | null;
        };
        /**
         * @description Types of auditable events.
         * @enum {string}
         */
        AuditEventType: "wallet_created" | "wallet_deleted" | "wallet_accessed" | "transaction_signed" | "transaction_broadcast" | "bookmark_created" | "bookmark_deleted" | "invite_created" | "invite_redeemed" | "recurring_created" | "recurring_updated" | "recurring_deleted" | "recurring_executed" | "auth_success" | "auth_failure" | "permission_denied" | "admin_access" | "config_changed";
        /** @description Response for audit log queries. */
        AuditLogResponse: {
            /** @description Audit events matching the query. */
            events: components["schemas"]["AuditEvent"][];
            /** @description Whether there are more results. */
            has_more: boolean;
            /** @description Total count (before limit/offset). */
            total: number;
        };
        /** @description Balance response. */
        BalanceResponse: components["schemas"]["WalletBalanceResponse"] & {
            /** @description Wallet ID */
            wallet_id: string;
        };
        Bookmark: {
            address: components["schemas"]["WalletAddress"];
            id: string;
            name: string;
            wallet_id: components["schemas"]["WalletAddress"];
        };
        CreateBookmarkRequest: {
            address: components["schemas"]["WalletAddress"];
            name: string;
            wallet_id: components["schemas"]["WalletAddress"];
        };
        CreateRecurringPaymentRequest: {
            /** Format: double */
            amount: number;
            currency_code: string;
            /** Format: int32 */
            frequency: number;
            /** Format: int32 */
            payment_end_date: number;
            /** Format: int32 */
            payment_start_date: number;
            recipient: components["schemas"]["WalletAddress"];
            wallet_id: components["schemas"]["WalletAddress"];
            wallet_public_key: string;
        };
        /** @description Request to create a new wallet. */
        CreateWalletRequest: {
            /** @description Optional human-readable label for the wallet. */
            label?: string | null;
        };
        /** @description Response after creating a wallet. */
        CreateWalletResponse: {
            /** @description Message indicating success. */
            message: string;
            /** @description The created wallet details. */
            wallet: components["schemas"]["WalletResponse"];
        };
        /** @description Response after deleting a wallet. */
        DeleteWalletResponse: {
            /** @description Message indicating success. */
            message: string;
            /** @description The ID of the deleted wallet. */
            wallet_id: string;
        };
        /** @description Detailed health check response for admins. */
        DetailedHealthResponse: {
            /** @description Auth configuration status. */
            auth_configured: boolean;
            /** @description Build timestamp. */
            build_time: string;
            /** @description Overall status. */
            status: string;
            /** @description Storage health. */
            storage: components["schemas"]["StorageHealth"];
            /** @description Server version. */
            version: string;
        };
        /** @description Individual health check results. */
        HealthChecks: {
            /** @description Data directory availability (if configured). */
            data_dir?: string | null;
            /**
             * @description JWKS (authentication keys) status.
             *     Only present in production mode (CLERK_JWKS_URL configured).
             */
            jwks?: string | null;
            /** @description Whether the service process is running. */
            service: string;
        };
        /** @description Simple health check response for liveness probes. */
        HealthResponse: {
            status: string;
        };
        Invite: {
            code: string;
            id: string;
            redeemed: boolean;
        };
        /** @description Native token balance response (simpler version). */
        NativeBalanceResponse: {
            /** @description Public address */
            address: string;
            /** @description AVAX balance formatted */
            balance: string;
            /** @description AVAX balance in wei */
            balance_wei: string;
            /** @description Network name */
            network: string;
            /** @description Wallet ID */
            wallet_id: string;
        };
        /** @description Health check response with individual component status. */
        ReadyResponse: {
            /** @description Individual health checks and their results. */
            checks: components["schemas"]["HealthChecks"];
            /** @description Overall health status ("ok" or "degraded"). */
            status: string;
        };
        RecurringPayment: {
            /** Format: double */
            amount: number;
            currency_code: string;
            /** Format: int32 */
            frequency: number;
            id: string;
            /** Format: int32 */
            last_paid_date: number;
            /** Format: int32 */
            payment_end_date: number;
            /** Format: int32 */
            payment_start_date: number;
            recipient: components["schemas"]["WalletAddress"];
            wallet_id: components["schemas"]["WalletAddress"];
            wallet_public_key: string;
        };
        RedeemInviteRequest: {
            invite_id: string;
        };
        /**
         * @description User roles for authorization.
         *
         *     ## Role Hierarchy
         *
         *     - `Admin` - Full access to all endpoints and wallets
         *     - `Client` - Normal user, can only access own wallets
         *     - `Support` - Read-only access to metadata (no private keys)
         *     - `Auditor` - Read-only access to audit logs
         * @enum {string}
         */
        Role: "admin" | "client" | "support" | "auditor";
        /** @description Storage health details. */
        StorageHealth: {
            /** @description Data directory path. */
            data_dir: string;
            /** @description Whether the data directory exists. */
            exists: boolean;
            /** @description Total files in storage (approximate). */
            total_files: number;
            /** @description Whether the data directory is writable. */
            writable: boolean;
        };
        /** @description System statistics response. */
        SystemStatsResponse: {
            /** @description Number of active wallets. */
            active_wallets: number;
            /** @description Number of deleted wallets. */
            deleted_wallets: number;
            /** @description Number of redeemed invites. */
            redeemed_invites: number;
            /** @description Number of suspended wallets. */
            suspended_wallets: number;
            /** @description Current timestamp. */
            timestamp: string;
            /** @description Total number of bookmarks. */
            total_bookmarks: number;
            /** @description Total number of invites. */
            total_invites: number;
            /** @description Total number of recurring payments. */
            total_recurring_payments: number;
            /** @description Total number of wallets across all users. */
            total_wallets: number;
            /**
             * Format: int64
             * @description Server uptime information.
             */
            uptime_seconds: number;
        };
        /** @description Token balance information. */
        TokenBalance: {
            /** @description Balance formatted with decimals */
            balance_formatted: string;
            /** @description Balance in smallest unit (wei for native, token decimals for ERC-20) */
            balance_raw: string;
            /** @description Contract address (None for native token) */
            contract_address?: string | null;
            /**
             * Format: int32
             * @description Number of decimals
             */
            decimals: number;
            /** @description Token name */
            name: string;
            /** @description Token symbol (e.g., "AVAX", "EUROC") */
            symbol: string;
        };
        UpdateLastPaidDateRequest: {
            /** Format: int32 */
            last_paid_date: number;
            recurring_payment_id: string;
        };
        UpdateRecurringPaymentRequest: {
            /** Format: double */
            amount: number;
            currency_code: string;
            /** Format: int32 */
            frequency: number;
            /** Format: int32 */
            payment_end_date: number;
            /** Format: int32 */
            payment_start_date: number;
            recipient: components["schemas"]["WalletAddress"];
            recurring_payment_id: string;
            wallet_id: components["schemas"]["WalletAddress"];
            wallet_public_key: string;
        };
        /** @description Response for GET /v1/users/me */
        UserMeResponse: {
            /** @description User's role */
            role: components["schemas"]["Role"];
            /** @description Session ID (if available) */
            session_id?: string | null;
            /** @description User's unique ID (from Clerk) */
            user_id: string;
        };
        WalletAddress: string;
        /** @description Wallet balance response including native and token balances. */
        WalletBalanceResponse: {
            /** @description Wallet address */
            address: string;
            /**
             * Format: int64
             * @description Chain ID
             */
            chain_id: number;
            /** @description Native token balance (AVAX) */
            native_balance: components["schemas"]["TokenBalance"];
            /** @description Network name */
            network: string;
            /** @description ERC-20 token balances */
            token_balances: components["schemas"]["TokenBalance"][];
        };
        /** @description Response containing a list of wallets. */
        WalletListResponse: {
            /** @description Total count of wallets. */
            total: number;
            /** @description List of wallets owned by the user. */
            wallets: components["schemas"]["WalletResponse"][];
        };
        /** @description Response returned to API clients (never includes private key). */
        WalletResponse: {
            /**
             * Format: date-time
             * @description When the wallet was created
             */
            created_at: string;
            /** @description Optional human-readable label */
            label?: string | null;
            /** @description Public address */
            public_address: string;
            /** @description Current wallet status */
            status: components["schemas"]["WalletStatus"];
            /** @description Unique wallet identifier */
            wallet_id: string;
        };
        /**
         * @description Wallet status.
         * @enum {string}
         */
        WalletStatus: "active" | "suspended" | "deleted";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service is unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    query_audit_logs: {
        parameters: {
            query?: {
                /** @description Start date (YYYY-MM-DD format). */
                start_date?: string | null;
                /** @description End date (YYYY-MM-DD format). */
                end_date?: string | null;
                /** @description Filter by user ID. */
                user_id?: string | null;
                /** @description Filter by event type. */
                event_type?: string | null;
                /** @description Filter by resource type. */
                resource_type?: string | null;
                /** @description Filter by resource ID. */
                resource_id?: string | null;
                /** @description Maximum number of results (default 100). */
                limit?: number | null;
                /** @description Offset for pagination. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponse"];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_detailed_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detailed health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedHealthResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_system_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatsResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_all_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_all_wallets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All wallets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWalletListResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activate_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suspend_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet suspended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_bookmarks: {
        parameters: {
            query: {
                wallet_id: components["schemas"]["WalletAddress"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_bookmark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookmarkRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_bookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the bookmark to delete */
                bookmark_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your bookmark */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bookmark not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_invite: {
        parameters: {
            query: {
                invite_code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
        };
    };
    redeem_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemInviteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_recurring_payment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringPaymentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_recurring_payment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the recurring payment to update */
                recurring_payment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringPaymentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_recurring_payment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the recurring payment to delete */
                recurring_payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_last_paid_date: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the recurring payment to update */
                recurring_payment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLastPaidDateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_recurring_payments: {
        parameters: {
            query: {
                wallet_id: components["schemas"]["WalletAddress"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringPayment"][];
                };
            };
        };
    };
    recurring_payments_today: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringPayment"][];
                };
            };
        };
    };
    get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_wallets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of wallets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWalletRequest"];
            };
        };
        responses: {
            /** @description Wallet created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateWalletResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wallet ID to delete */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteWalletResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_wallet_balance: {
        parameters: {
            query?: {
                /** @description Network to query: "fuji" (testnet) or "mainnet" */
                network?: string | null;
                /** @description Additional token contract addresses to query (comma-separated) */
                tokens?: string | null;
            };
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not wallet owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Blockchain network unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_native_balance: {
        parameters: {
            query?: {
                /** @description Network to query: "fuji" (testnet) or "mainnet" */
                network?: string | null;
                /** @description Additional token contract addresses to query (comma-separated) */
                tokens?: string | null;
            };
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Native balance retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeBalanceResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not wallet owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Blockchain network unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
