/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint handler.
         * @description Returns 200 if all checks pass, 503 if any check fails.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe handler.
         * @description Always returns 200 if the process is running.
         *     Does not check dependencies - use readiness for that.
         */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe handler.
         * @description Returns 200 only if all dependencies are available.
         *     Use for Kubernetes readiness probes.
         */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query audit logs.
         * @description Search and filter audit log entries. Supports date range, user ID,
         *     event type, and resource filtering. Admin only.
         */
        get: operations["query_audit_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed health information.
         * @description Returns comprehensive health status including storage metrics.
         *     More detailed than the public health endpoint. Admin only.
         */
        get: operations["get_detailed_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system statistics.
         * @description Returns aggregate statistics about the system including wallet counts,
         *     invite usage, and storage metrics. Admin only.
         */
        get: operations["get_system_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all unique users with their resource counts.
         * @description Returns a summary of all users who have wallets, bookmarks, or recurring payments.
         */
        get: operations["list_all_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all wallets (admin view).
         * @description Returns all wallets across all users. Admin only.
         */
        get: operations["list_all_wallets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/wallets/{wallet_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reactivate a suspended wallet (admin action).
         * @description Reactivates a previously suspended wallet.
         */
        post: operations["activate_wallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/wallets/{wallet_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend a wallet (admin action).
         * @description Suspends a wallet by ID. The wallet owner cannot perform operations
         *     on suspended wallets until reactivated.
         */
        post: operations["suspend_wallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bookmarks for a wallet.
         * @description Returns all bookmarks for a wallet owned by the authenticated user.
         */
        get: operations["list_bookmarks"];
        put?: never;
        /**
         * Create a new bookmark.
         * @description Creates a bookmark in a wallet owned by the authenticated user.
         */
        post: operations["create_bookmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookmarks/{bookmark_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a bookmark.
         * @description Deletes a bookmark owned by the authenticated user.
         */
        delete: operations["delete_bookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiat/offramp/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create fiat off-ramp request. */
        post: operations["create_offramp_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiat/onramp/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create fiat on-ramp request. */
        post: operations["create_onramp_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiat/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported fiat providers for sandbox testing. */
        get: operations["list_fiat_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiat/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List fiat requests for current user. */
        get: operations["list_fiat_requests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiat/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get fiat request by ID. */
        get: operations["get_fiat_request"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_invite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invite/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["redeem_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_recurring_payment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payment/{recurring_payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_recurring_payment"];
        post?: never;
        delete: operations["delete_recurring_payment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payment/{recurring_payment_id}/last-paid-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_last_paid_date"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_recurring_payments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring/payments/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recurring_payments_today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current authenticated user's information.
         * @description This endpoint returns the identity and roles of the currently authenticated user.
         */
        get: operations["get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all wallets owned by the authenticated user. */
        get: operations["list_wallets"];
        put?: never;
        /**
         * Create a new wallet for the authenticated user.
         * @description Generates a new p256 keypair inside the SGX enclave and stores it
         *     encrypted on disk. Returns the wallet metadata (never the private key).
         */
        post: operations["create_wallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific wallet by ID.
         * @description Only returns wallets owned by the authenticated user.
         */
        get: operations["get_wallet"];
        put?: never;
        post?: never;
        /**
         * Delete (soft-delete) a wallet.
         * @description Marks the wallet as deleted. The private key is retained for potential
         *     recovery but the wallet cannot be used for new transactions.
         */
        delete: operations["delete_wallet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the balance of a wallet on the Avalanche C-Chain.
         * @description Returns native AVAX balance and any configured ERC-20 token balances.
         */
        get: operations["get_wallet_balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}/balance/native": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get only the native AVAX balance of a wallet (faster). */
        get: operations["get_native_balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Estimate gas for a transaction.
         * @description Returns estimated gas limit and cost before sending.
         */
        post: operations["estimate_gas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a transaction from a wallet.
         * @description Signs the transaction inside the SGX enclave and broadcasts to the network.
         */
        post: operations["send_transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions for a wallet. */
        get: operations["list_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{wallet_id}/transactions/{tx_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of a specific transaction.
         * @description Used for polling after send. Updates stored status from blockchain if pending.
         */
        get: operations["get_transaction_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response for admin user list. */
        AdminUserListResponse: {
            /** @description Total unique users. */
            total: number;
            /** @description User summaries. */
            users: components["schemas"]["AdminUserSummary"][];
        };
        /** @description Admin user summary. */
        AdminUserSummary: {
            /** @description Number of bookmarks. */
            bookmark_count: number;
            /** @description Number of recurring payments. */
            recurring_payment_count: number;
            /** @description User ID from Clerk. */
            user_id: string;
            /** @description Number of wallets owned. */
            wallet_count: number;
        };
        /** @description Admin wallet list item (shows all wallets regardless of owner). */
        AdminWalletItem: {
            /** @description When the wallet was created. */
            created_at: string;
            /** @description Owner's user ID. */
            owner_user_id: string;
            /** @description Public address. */
            public_address: string;
            /** @description Wallet status. */
            status: components["schemas"]["WalletStatus"];
            /** @description Wallet unique identifier. */
            wallet_id: string;
        };
        /** @description Response for admin wallet list. */
        AdminWalletListResponse: {
            /** @description Total count. */
            total: number;
            /** @description List of all wallets. */
            wallets: components["schemas"]["AdminWalletItem"][];
        };
        /** @description An audit log entry. */
        AuditEvent: {
            /** @description Additional details as JSON. */
            details?: Record<string, never> | null;
            /** @description Error message if operation failed. */
            error?: string | null;
            /** @description Unique event ID. */
            event_id: string;
            /** @description Type of event. */
            event_type: components["schemas"]["AuditEventType"];
            /** @description IP address of the request (if available). */
            ip_address?: string | null;
            /** @description Resource affected (wallet_id, bookmark_id, etc.). */
            resource_id?: string | null;
            /** @description Resource type (wallet, bookmark, etc.). */
            resource_type?: string | null;
            /** @description Whether the operation succeeded. */
            success: boolean;
            /**
             * Format: date-time
             * @description When the event occurred.
             */
            timestamp: string;
            /** @description User who triggered the event (if known). */
            user_id?: string | null;
        };
        /**
         * @description Types of auditable events.
         * @enum {string}
         */
        AuditEventType: "wallet_created" | "wallet_deleted" | "wallet_accessed" | "transaction_signed" | "transaction_broadcast" | "bookmark_created" | "bookmark_deleted" | "invite_created" | "invite_redeemed" | "recurring_created" | "recurring_updated" | "recurring_deleted" | "recurring_executed" | "auth_success" | "auth_failure" | "permission_denied" | "admin_access" | "config_changed" | "fiat_on_ramp_requested" | "fiat_off_ramp_requested";
        /** @description Response for audit log queries. */
        AuditLogResponse: {
            /** @description Audit events matching the query. */
            events: components["schemas"]["AuditEvent"][];
            /** @description Whether there are more results. */
            has_more: boolean;
            /** @description Total count (before limit/offset). */
            total: number;
        };
        /** @description Balance response. */
        BalanceResponse: components["schemas"]["WalletBalanceResponse"] & {
            /** @description Wallet ID */
            wallet_id: string;
        };
        /**
         * @description A saved wallet address bookmark.
         *
         *     Bookmarks allow users to save frequently-used addresses with friendly names
         *     for quick access when sending transactions.
         */
        Bookmark: {
            /** @description The bookmarked wallet address. */
            address: components["schemas"]["WalletAddress"];
            /** @description Unique identifier for this bookmark. */
            id: string;
            /** @description User-friendly name for the bookmarked address. */
            name: string;
            /** @description The wallet this bookmark belongs to. */
            wallet_id: components["schemas"]["WalletAddress"];
        };
        /** @description Request to create a new bookmark. */
        CreateBookmarkRequest: {
            /** @description The wallet address to bookmark. */
            address: components["schemas"]["WalletAddress"];
            /** @description User-friendly name for the bookmark. */
            name: string;
            /** @description The wallet to add the bookmark to (must be owned by the user). */
            wallet_id: components["schemas"]["WalletAddress"];
        };
        /** @description Request body for creating fiat on-ramp/off-ramp requests. */
        CreateFiatRequest: {
            /** @description Amount in EUR decimal string (e.g. "25.50"). */
            amount_eur: string;
            /** @description Beneficiary account holder name (required for off-ramp). */
            beneficiary_account_holder_name?: string | null;
            /** @description Beneficiary IBAN (required for off-ramp). */
            beneficiary_iban?: string | null;
            /** @description Optional free-form note. */
            note?: string | null;
            /** @description Optional provider name (`truelayer_sandbox` default). */
            provider?: string | null;
            /** @description Wallet to credit/debit for this fiat request. */
            wallet_id: string;
        };
        /** @description Request to create a recurring payment schedule. */
        CreateRecurringPaymentRequest: {
            /**
             * Format: double
             * @description Payment amount.
             */
            amount: number;
            /** @description Currency code (e.g., "AVAX", "USDC"). */
            currency_code: string;
            /**
             * Format: int32
             * @description Frequency in days between payments.
             */
            frequency: number;
            /**
             * Format: int32
             * @description End date (Unix timestamp in days, 0 = no end).
             */
            payment_end_date: number;
            /**
             * Format: int32
             * @description Start date (Unix timestamp in days).
             */
            payment_start_date: number;
            /** @description Recipient address for payments. */
            recipient: components["schemas"]["WalletAddress"];
            /** @description The source wallet (must be owned by the user). */
            wallet_id: components["schemas"]["WalletAddress"];
            /** @description Public key for the wallet. */
            wallet_public_key: string;
        };
        /** @description Request to create a new wallet. */
        CreateWalletRequest: {
            /** @description Optional human-readable label for the wallet. */
            label?: string | null;
        };
        /** @description Response after creating a wallet. */
        CreateWalletResponse: {
            /** @description Message indicating success. */
            message: string;
            /** @description The created wallet details. */
            wallet: components["schemas"]["WalletResponse"];
        };
        /** @description Response after deleting a wallet. */
        DeleteWalletResponse: {
            /** @description Message indicating success. */
            message: string;
            /** @description The ID of the deleted wallet. */
            wallet_id: string;
        };
        /** @description Detailed health check response for admins. */
        DetailedHealthResponse: {
            /** @description Auth configuration status. */
            auth_configured: boolean;
            /** @description Build timestamp. */
            build_time: string;
            /** @description Overall status. */
            status: string;
            /** @description Storage health. */
            storage: components["schemas"]["StorageHealth"];
            /** @description Server version. */
            version: string;
        };
        /** @description Request to estimate gas for a transaction. */
        EstimateGasRequest: {
            /** @description Amount to send in human-readable format (e.g., "1.5") */
            amount: string;
            /** @description Network: "fuji" (default) or "mainnet" */
            network?: string;
            /** @description Recipient address (0x + 40 hex chars) */
            to: string;
            /** @description Token type: "native" for AVAX or contract address for ERC-20 */
            token?: string;
        };
        /** @description Gas estimation response. */
        EstimateGasResponse: {
            /** @description Total estimated cost in AVAX */
            estimated_cost: string;
            /** @description Total estimated cost in wei */
            estimated_cost_wei: string;
            /** @description Estimated gas limit */
            gas_limit: string;
            /** @description Max fee per gas in wei */
            max_fee_per_gas: string;
            /** @description Max priority fee per gas in wei */
            max_priority_fee_per_gas: string;
        };
        /**
         * @description Fiat request direction.
         * @enum {string}
         */
        FiatDirection: "on_ramp" | "off_ramp";
        /** @description Response for provider discovery. */
        FiatProviderListResponse: {
            /** @description Default provider ID if client does not pass one. */
            default_provider: string;
            /** @description Providers currently enabled by backend. */
            providers: components["schemas"]["FiatProviderSummary"][];
        };
        /** @description Provider summary exposed by fiat API. */
        FiatProviderSummary: {
            /** @description Human-friendly provider name for UI display. */
            display_name: string;
            /** @description Whether backend is configured and ready for this provider. */
            enabled: boolean;
            /** @description Stable provider ID used by API requests. */
            provider_id: string;
            /** @description Indicates this provider is sandbox-only in current environment. */
            sandbox: boolean;
            /** @description Whether the provider can process off-ramp requests. */
            supports_off_ramp: boolean;
            /** @description Whether the provider can process on-ramp requests. */
            supports_on_ramp: boolean;
        };
        /** @description List response for fiat requests. */
        FiatRequestListResponse: {
            /** @description Requests visible to the authenticated user. */
            requests: components["schemas"]["FiatRequestResponse"][];
            /** @description Total count. */
            total: number;
        };
        /** @description Fiat request response returned to clients. */
        FiatRequestResponse: {
            /** @description Amount in EUR. */
            amount_eur: string;
            /** @description Creation time. */
            created_at: string;
            /** @description `on_ramp` or `off_ramp`. */
            direction: components["schemas"]["FiatDirection"];
            /** @description Optional note. */
            note?: string | null;
            /** @description Provider identifier. */
            provider: string;
            /** @description Optional provider action URL (for redirect/continue flow). */
            provider_action_url?: string | null;
            /** @description Optional provider reference/session ID. */
            provider_reference?: string | null;
            /** @description Request ID. */
            request_id: string;
            /** @description Current status. */
            status: components["schemas"]["FiatRequestStatus"];
            /** @description Last update time. */
            updated_at: string;
            /** @description Wallet ID tied to this request. */
            wallet_id: string;
        };
        /**
         * @description Fiat request lifecycle status.
         * @enum {string}
         */
        FiatRequestStatus: "queued" | "provider_pending" | "completed" | "failed";
        /** @description Individual health check results. */
        HealthChecks: {
            /** @description Data directory availability (if configured). */
            data_dir?: string | null;
            /** @description Whether the service process is running. */
            service: string;
        };
        /** @description Simple health check response for liveness probes. */
        HealthResponse: {
            status: string;
        };
        /**
         * @description An invitation code for new users.
         *
         *     Invites can be used to control access to the wallet service. Each invite
         *     code can only be redeemed once.
         */
        Invite: {
            /** @description The invite code (shared with the invitee). */
            code: string;
            /** @description Unique identifier for this invite. */
            id: string;
            /** @description Whether this invite has been used. */
            redeemed: boolean;
        };
        /** @description Native token balance response (simpler version). */
        NativeBalanceResponse: {
            /** @description Public address */
            address: string;
            /** @description AVAX balance formatted */
            balance: string;
            /** @description AVAX balance in wei */
            balance_wei: string;
            /** @description Network name */
            network: string;
            /** @description Wallet ID */
            wallet_id: string;
        };
        /** @description Health check response with individual component status. */
        ReadyResponse: {
            /** @description Individual health checks and their results. */
            checks: components["schemas"]["HealthChecks"];
            /** @description Overall health status ("ok" or "degraded"). */
            status: string;
        };
        /**
         * @description A scheduled recurring payment configuration.
         *
         *     Recurring payments allow automatic transfers on a schedule. The actual
         *     execution logic is handled by a separate service.
         */
        RecurringPayment: {
            /**
             * Format: double
             * @description Payment amount.
             */
            amount: number;
            /** @description Currency code (e.g., "AVAX", "USDC"). */
            currency_code: string;
            /**
             * Format: int32
             * @description Frequency in days between payments.
             */
            frequency: number;
            /** @description Unique identifier for this payment schedule. */
            id: string;
            /**
             * Format: int32
             * @description Last payment date (Unix timestamp in days).
             */
            last_paid_date: number;
            /**
             * Format: int32
             * @description End date (Unix timestamp in days, 0 = no end).
             */
            payment_end_date: number;
            /**
             * Format: int32
             * @description Start date (Unix timestamp in days).
             */
            payment_start_date: number;
            /** @description The recipient address for payments. */
            recipient: components["schemas"]["WalletAddress"];
            /** @description The source wallet for payments. */
            wallet_id: components["schemas"]["WalletAddress"];
            /** @description Public key of the wallet (for verification). */
            wallet_public_key: string;
        };
        /** @description Request to redeem an invite code. */
        RedeemInviteRequest: {
            /** @description The invite ID to redeem. */
            invite_id: string;
        };
        /**
         * @description User roles for authorization.
         *
         *     ## Role Hierarchy
         *
         *     - `Admin` - Full access to all endpoints and wallets
         *     - `Client` - Normal user, can only access own wallets
         *     - `Support` - Read-only access to metadata (no private keys)
         *     - `Auditor` - Read-only access to audit logs
         * @enum {string}
         */
        Role: "admin" | "client" | "support" | "auditor";
        /** @description Request to send a transaction. */
        SendTransactionRequest: {
            /** @description Amount to send in human-readable format (e.g., "1.5") */
            amount: string;
            /** @description Optional gas limit override */
            gas_limit?: string | null;
            /** @description Optional max priority fee per gas override (in wei) */
            max_priority_fee_per_gas?: string | null;
            /** @description Network: "fuji" (default) or "mainnet" */
            network?: string;
            /** @description Recipient address (0x + 40 hex chars) */
            to: string;
            /** @description Token type: "native" for AVAX or contract address for ERC-20 */
            token?: string;
        };
        /** @description Transaction send response. */
        SendTransactionResponse: {
            /** @description Block explorer URL */
            explorer_url: string;
            /** @description Current status */
            status: string;
            /** @description Transaction hash */
            tx_hash: string;
        };
        /** @description Storage health details. */
        StorageHealth: {
            /** @description Data directory path. */
            data_dir: string;
            /** @description Whether the data directory exists. */
            exists: boolean;
            /** @description Total files in storage (approximate). */
            total_files: number;
            /** @description Whether the data directory is writable. */
            writable: boolean;
        };
        /** @description Persisted fiat request record. */
        StoredFiatRequest: {
            /** @description Requested fiat amount in EUR (human-readable decimal string). */
            amount_eur: string;
            /**
             * Format: date-time
             * @description Creation timestamp.
             */
            created_at: string;
            /** @description On-ramp vs off-ramp direction. */
            direction: components["schemas"]["FiatDirection"];
            /** @description Optional user note. */
            note?: string | null;
            /** @description Owner user ID. */
            owner_user_id: string;
            /** @description Selected provider identifier (stub: `truelayer_sandbox`). */
            provider: string;
            /** @description Optional URL where user can continue provider authorization. */
            provider_action_url?: string | null;
            /** @description Optional provider reference/session ID. */
            provider_reference?: string | null;
            /** @description Unique request identifier. */
            request_id: string;
            /** @description Current status. */
            status: components["schemas"]["FiatRequestStatus"];
            /**
             * Format: date-time
             * @description Last update timestamp.
             */
            updated_at: string;
            /** @description Wallet tied to this request. */
            wallet_id: string;
        };
        /** @description Stored transaction record. */
        StoredTransaction: {
            /** @description Amount in human-readable format */
            amount: string;
            /**
             * Format: int64
             * @description Block number (if confirmed)
             */
            block_number?: number | null;
            /** @description Optional counterparty wallet ID when both sides are internal wallets. */
            counterparty_wallet_id?: string | null;
            /**
             * Format: date-time
             * @description When the transaction was submitted
             */
            created_at: string;
            /** @description Block explorer URL */
            explorer_url: string;
            /** @description Sender address */
            from: string;
            /**
             * Format: int64
             * @description Gas used (if confirmed)
             */
            gas_used?: number | null;
            /** @description Network (fuji or mainnet) */
            network: string;
            /** @description Current transaction status */
            status: components["schemas"]["TxStatus"];
            /** @description Recipient address */
            to: string;
            /** @description Token type (native or ERC-20) */
            token: components["schemas"]["TokenType"];
            /** @description Transaction hash (0x prefixed) */
            tx_hash: string;
            /**
             * Format: date-time
             * @description When the status was last updated
             */
            updated_at: string;
            /** @description Wallet ID that initiated the transaction */
            wallet_id: string;
        };
        /** @description System statistics response. */
        SystemStatsResponse: {
            /** @description Number of active wallets. */
            active_wallets: number;
            /** @description Number of deleted wallets. */
            deleted_wallets: number;
            /** @description Number of redeemed invites. */
            redeemed_invites: number;
            /** @description Number of suspended wallets. */
            suspended_wallets: number;
            /** @description Current timestamp. */
            timestamp: string;
            /** @description Total number of bookmarks. */
            total_bookmarks: number;
            /** @description Total number of invites. */
            total_invites: number;
            /** @description Total number of recurring payments. */
            total_recurring_payments: number;
            /** @description Total number of wallets across all users. */
            total_wallets: number;
            /**
             * Format: int64
             * @description Server uptime information.
             */
            uptime_seconds: number;
        };
        /** @description Token balance information. */
        TokenBalance: {
            /** @description Balance formatted with decimals */
            balance_formatted: string;
            /** @description Balance in smallest unit (wei for native, token decimals for ERC-20) */
            balance_raw: string;
            /** @description Contract address (None for native token) */
            contract_address?: string | null;
            /**
             * Format: int32
             * @description Number of decimals
             */
            decimals: number;
            /** @description Token name */
            name: string;
            /** @description Token symbol (e.g., "AVAX", "EUROC") */
            symbol: string;
        };
        /** @description Token type for a transaction. */
        TokenType: "native" | {
            /** @description ERC-20 token transfer (stores contract address) */
            erc20: string;
        };
        /** @description Transaction list response. */
        TransactionListResponse: {
            /** @description List of transactions */
            transactions: components["schemas"]["TransactionSummary"][];
        };
        /** @description Transaction status response. */
        TransactionStatusResponse: {
            /**
             * Format: int64
             * @description Block number (if confirmed)
             */
            block_number?: number | null;
            /**
             * Format: int64
             * @description Number of confirmations
             */
            confirmations?: number | null;
            /** @description Gas used (if confirmed) */
            gas_used?: string | null;
            /** @description Status: pending, confirmed, failed */
            status: string;
            /** @description Timestamp */
            timestamp?: string | null;
            /** @description Transaction hash */
            tx_hash: string;
        };
        /** @description Transaction summary for list view. */
        TransactionSummary: {
            /** @description Amount sent */
            amount: string;
            /**
             * Format: int64
             * @description Block number (if confirmed)
             */
            block_number?: number | null;
            /** @description Direction: "sent" or "received" */
            direction: string;
            /** @description Block explorer URL */
            explorer_url: string;
            /** @description Sender address */
            from: string;
            /** @description Network */
            network: string;
            /** @description Status: pending, confirmed, failed */
            status: string;
            /** @description Timestamp */
            timestamp: string;
            /** @description Recipient address */
            to: string;
            /** @description Token type */
            token: string;
            /** @description Transaction hash */
            tx_hash: string;
        };
        /**
         * @description Transaction status.
         * @enum {string}
         */
        TxStatus: "pending" | "confirmed" | "failed";
        /** @description Request to update the last paid date for a recurring payment. */
        UpdateLastPaidDateRequest: {
            /**
             * Format: int32
             * @description New last paid date (Unix timestamp in days).
             */
            last_paid_date: number;
            /** @description ID of the recurring payment. */
            recurring_payment_id: string;
        };
        /** @description Request to update an existing recurring payment. */
        UpdateRecurringPaymentRequest: {
            /**
             * Format: double
             * @description Updated payment amount.
             */
            amount: number;
            /** @description Updated currency code. */
            currency_code: string;
            /**
             * Format: int32
             * @description Updated frequency.
             */
            frequency: number;
            /**
             * Format: int32
             * @description Updated end date.
             */
            payment_end_date: number;
            /**
             * Format: int32
             * @description Updated start date.
             */
            payment_start_date: number;
            /** @description Updated recipient address. */
            recipient: components["schemas"]["WalletAddress"];
            /** @description ID of the recurring payment to update. */
            recurring_payment_id: string;
            /** @description Updated source wallet. */
            wallet_id: components["schemas"]["WalletAddress"];
            /** @description Updated public key. */
            wallet_public_key: string;
        };
        /** @description Response for GET /v1/users/me */
        UserMeResponse: {
            /** @description User's role */
            role: components["schemas"]["Role"];
            /** @description Session ID (if available) */
            session_id?: string | null;
            /** @description User's unique ID (from Clerk) */
            user_id: string;
        };
        /**
         * @description Ethereum-compatible wallet address wrapper.
         *
         *     Provides type safety for wallet addresses throughout the API.
         *     Format: `0x` followed by 40 hexadecimal characters (20 bytes).
         *
         *     # Example
         *
         *     ```rust,ignore
         *     let addr = WalletAddress::from("0x742d35Cc6634C0532925a3b844Bc9e7595f4aB12");
         *     ```
         */
        WalletAddress: string;
        /** @description Wallet balance response including native and token balances. */
        WalletBalanceResponse: {
            /** @description Wallet address */
            address: string;
            /**
             * Format: int64
             * @description Chain ID
             */
            chain_id: number;
            /** @description Native token balance (AVAX) */
            native_balance: components["schemas"]["TokenBalance"];
            /** @description Network name */
            network: string;
            /** @description ERC-20 token balances */
            token_balances: components["schemas"]["TokenBalance"][];
        };
        /** @description Response containing a list of wallets. */
        WalletListResponse: {
            /** @description Total count of wallets. */
            total: number;
            /** @description List of wallets owned by the user. */
            wallets: components["schemas"]["WalletResponse"][];
        };
        /** @description Response returned to API clients (never includes private key). */
        WalletResponse: {
            /**
             * Format: date-time
             * @description When the wallet was created
             */
            created_at: string;
            /** @description Optional human-readable label */
            label?: string | null;
            /** @description Public address */
            public_address: string;
            /** @description Current wallet status */
            status: components["schemas"]["WalletStatus"];
            /** @description Unique wallet identifier */
            wallet_id: string;
        };
        /**
         * @description Wallet status.
         * @enum {string}
         */
        WalletStatus: "active" | "suspended" | "deleted";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service is unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    query_audit_logs: {
        parameters: {
            query?: {
                /** @description Start date (YYYY-MM-DD format). */
                start_date?: string | null;
                /** @description End date (YYYY-MM-DD format). */
                end_date?: string | null;
                /** @description Filter by user ID. */
                user_id?: string | null;
                /** @description Filter by event type. */
                event_type?: string | null;
                /** @description Filter by resource type. */
                resource_type?: string | null;
                /** @description Filter by resource ID. */
                resource_id?: string | null;
                /** @description Maximum number of results (default 100). */
                limit?: number | null;
                /** @description Offset for pagination. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponse"];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_detailed_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detailed health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedHealthResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_system_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatsResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_all_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_all_wallets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All wallets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWalletListResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activate_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suspend_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet suspended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized (admin required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_bookmarks: {
        parameters: {
            query: {
                wallet_id: components["schemas"]["WalletAddress"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_bookmark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookmarkRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_bookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the bookmark to delete */
                bookmark_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your bookmark */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bookmark not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_offramp_request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFiatRequest"];
            };
        };
        responses: {
            /** @description Fiat off-ramp request created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiatRequestResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_onramp_request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFiatRequest"];
            };
        };
        responses: {
            /** @description Fiat on-ramp request created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiatRequestResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_fiat_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported fiat providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiatProviderListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_fiat_requests: {
        parameters: {
            query?: {
                /** @description Optional wallet filter. */
                wallet_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fiat requests listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiatRequestListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_fiat_request: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fiat request ID */
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fiat request details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiatRequestResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_invite: {
        parameters: {
            query: {
                invite_code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
        };
    };
    redeem_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemInviteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_recurring_payment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringPaymentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_recurring_payment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the recurring payment to update */
                recurring_payment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringPaymentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_recurring_payment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the recurring payment to delete */
                recurring_payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_last_paid_date: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the recurring payment to update */
                recurring_payment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLastPaidDateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_recurring_payments: {
        parameters: {
            query: {
                wallet_id: components["schemas"]["WalletAddress"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringPayment"][];
                };
            };
        };
    };
    recurring_payments_today: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringPayment"][];
                };
            };
        };
    };
    get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Unauthorized - invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_wallets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of wallets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWalletRequest"];
            };
        };
        responses: {
            /** @description Wallet created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateWalletResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wallet ID to delete */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteWalletResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_wallet_balance: {
        parameters: {
            query?: {
                /** @description Network to query: "fuji" (testnet) or "mainnet" */
                network?: string | null;
                /** @description Additional token contract addresses to query (comma-separated) */
                tokens?: string | null;
            };
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not wallet owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Blockchain network unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_native_balance: {
        parameters: {
            query?: {
                /** @description Network to query: "fuji" (testnet) or "mainnet" */
                network?: string | null;
                /** @description Additional token contract addresses to query (comma-separated) */
                tokens?: string | null;
            };
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Native balance retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeBalanceResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not wallet owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Blockchain network unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    estimate_gas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateGasRequest"];
            };
        };
        responses: {
            /** @description Gas estimate calculated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateGasResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not wallet owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Blockchain network unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendTransactionResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not wallet owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient balance */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Blockchain network unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_transactions: {
        parameters: {
            query?: {
                /** @description Network filter: "fuji" or "mainnet" */
                network?: string | null;
                /** @description Maximum number of results (default: 50) */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not wallet owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_transaction_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wallet ID */
                wallet_id: string;
                /** @description Transaction hash */
                tx_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionStatusResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not wallet owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wallet or transaction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
