source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8"
gem "logger", "~> 1.6"
gem "just-the-docs", "~> 0.10.0"
gem "bigdecimal", "~> 3.3.1"

group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-include-cache", "~> 0.2.1"
end
